apiVersion: v1
kind: ConfigMap
metadata:
  name: shs-api-config
  namespace: shs
data:
  ASPNETCORE_HTTP_PORTS: "80"
  ASPNETCORE_HTTPS_PORTS: "443"
  JWT_ISSUER: "Second Hand EShop"
  WEBSITES_ENABLE_APP_SERVICE_STORAGE: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: shs-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=database-server,1433;Database=SecondHandEShopDB;User Id=sa;Password=MyC0mpl3xP@ssw0rd!;TrustServerCertificate=True;"
  JWT_SECRET: "Lep i suncan dan za objesiti se :)))))"
  JWT_ISSUER: "Second Hand EShop"
